In [ ]:
import torch
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("WARNING: No GPU. Runtime → Change runtime type → GPU")

CUDA available: True
GPU: Tesla T4

In [ ]:
!pip -q install "pandas>=2.0.0" "numpy>=1.24.0" "scikit-learn>=1.3.0" "scipy>=1.11.0" "matplotlib>=3.7.0"
!pip -q install "torch" "transformers>=4.40.0" "accelerate>=1.1.0"
print("Install done")

Install done

In [ ]:
from google.colab import files
from pathlib import Path

ZIP_NAME = "NLP_Package.zip"
zip_path = Path("/content") / ZIP_NAME
if not zip_path.is_file():
    print("Choose Files → select NLP_Package.zip")
    uploaded = files.upload()
    for name, data in uploaded.items():
        Path("/content", name).write_bytes(data)
        print("Saved:", name)
else:
    print("Already present:", zip_path)

Choose Files → select NLP_Package.zip

Saving NLP_Package.zip to NLP_Package.zip
Saved: NLP_Package.zip

In [ ]:
import zipfile, shutil
from pathlib import Path

zip_path = Path("/content/NLP_Package.zip")
assert zip_path.is_file(), "Re-run Cell 2 and upload NLP_Package.zip"

for name in ["care_notes_nlp_framework", "Synthetic_CareNotes_Dataset"]:
    p = Path("/content") / name
    if p.exists():
        shutil.rmtree(p)

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall("/content")

fw = Path("/content/care_notes_nlp_framework")
ds = Path("/content/Synthetic_CareNotes_Dataset")
print("Framework:", fw.is_dir())
print("Dataset:", ds.is_dir())
print("Corpus:", (ds / "care_notes_corpus.csv").is_file())
assert fw.is_dir() and (ds / "care_notes_corpus.csv").is_file()
print("Ready.")

Framework: True
Dataset: True
Corpus: True
Ready.

In [ ]:
import os, sys
os.chdir("/content/care_notes_nlp_framework")
sys.path.insert(0, "/content/care_notes_nlp_framework")
# Nine-step run: 7 models + best-two + random search (8a/8b) + hybrid
%run -i pipeline_seven_models_linear.py

======================================================================
NINE-STEP PIPELINE — SEVEN MODELS (linear, no custom functions)
FAST = True  N_ITER = 6
Dataset: /content/Synthetic_CareNotes_Dataset/care_notes_corpus.csv
======================================================================

STEP 1 — Clean dataset
Rows after cleaning: 4000

STEP 2 — Train/test split 70/30
Train: 2800  Test: 1200

STEP 3 — Balance training set ONLY
Balanced train: {0: 1400, 1: 1400}
Test unchanged: {1: 723, 0: 477}

STEP 4 — TF-IDF + Logistic Regression
  Accuracy: 0.8033  F1: 0.8066

STEP 5 — RNN models (LSTM, GRU, Bi-LSTM)
  Training LSTM...
  LSTM Accuracy: 0.7725  F1: 0.7708
  Training GRU...
  GRU Accuracy: 0.8025  F1: 0.804
  Training Bi-LSTM...
  Bi-LSTM Accuracy: 0.7775  F1: 0.781

STEP 6 — Transformer models
  Training DistilBERT...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

  DistilBERT Accuracy: 0.8692  F1: 0.8782  (29s)
  Training RoBERTa...

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  499MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

  RoBERTa Accuracy: 0.8692  F1: 0.8782  (26s)
  Training ModernBERT...

config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/20.8k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.13M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  599MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

  ModernBERT Accuracy: 0.7808  F1: 0.7777  (34s)

--- SEVEN-MODEL COMPARISON (combined escalation accuracy) ---
Model                  Accuracy       F1  Precision   Recall
DistilBERT               0.8692   0.8782     1.0000   0.7828
RoBERTa                  0.8692   0.8782     1.0000   0.7828
TF-IDF + LogReg          0.8033   0.8066     0.9899   0.6805
GRU                      0.8025   0.8040     1.0000   0.6722
ModernBERT               0.7808   0.7777     1.0000   0.6362
Bi-LSTM                  0.7775   0.7810     0.9597   0.6584
LSTM                     0.7725   0.7708     0.9808   0.6349

STEP 7 — Select best two models by accuracy
Best 1: DistilBERT 0.8692
Best 2: RoBERTa 0.8692

STEP 8a — Random search (independent): DistilBERT

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

  Best params: {'learning_rate': 1e-05, 'epochs': 2, 'batch_size': 32, 'weight_decay': 0.01, 'dropout': 0.31, 'max_length': 64}
  Test accuracy: 0.8692  F1: 0.8782  (78s)

STEP 8b — Random search (independent): RoBERTa

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

  Best params: {'learning_rate': 5e-05, 'epochs': 1, 'batch_size': 16, 'weight_decay': 0.1, 'dropout': 0.32, 'max_length': 96}
  Test accuracy: 0.8692  F1: 0.8782  (123s)

STEP 9 — Hybrid ensemble (50/50 tuned probabilities)
Hybrid accuracy: 0.8692  F1: 0.8782

Saving results to /content/care_notes_nlp_framework/results/linear_seven_model_pipeline

DONE.
Best two: DistilBERT + RoBERTa
Default / Tuned / Hybrid accuracy: 0.8692 / 0.8692 / 0.8692
Files saved in: /content/care_notes_nlp_framework/results/linear_seven_model_pipeline

In [ ]:
from pathlib import Path
src = Path("/content/care_notes_nlp_framework/pipeline_seven_models_linear.py")
text = src.read_text(encoding="utf-8")
print("Lines:", text.count("\n") + 1)
print(text)

Lines: 658
# -*- coding: utf-8 -*-
# =============================================================================
# Care Notes NLP — Full Nine-Step Pipeline (LINEAR CODE, NO CUSTOM FUNCTIONS)
# Seven-model comparison + best-two selection + random search + hybrid
#
# Models:
#   1. TF-IDF + Logistic Regression
#   2. LSTM
#   3. GRU
#   4. Bi-LSTM
#   5. DistilBERT
#   6. RoBERTa
#   7. ModernBERT
#
# Metric: combined escalation accuracy (65% text + 35% MODS, threshold 0.6)
#
# LOCAL run:
#   cd care_notes_nlp_framework
#   python pipeline_seven_models_linear.py
#
# COLAB: set RUN_ON_COLAB = True below, upload CSV + framework zip when prompted
# =============================================================================

# ---------- 0. SETTINGS ----------
RUN_ON_COLAB = False   # True on Google Colab
FAST = True            # shorter RNN/transformer training
N_ITER = 6             # random-search trials per best-two model
RANDOM_STATE = 42
TEST_SIZE = 0.30
THRESHOLD = 0.6
FUSION_TEXT = 0.65
FUSION_STRUCT = 0.35
TEXT_COL = "note_text"
LABEL_COL = "escalation_recommended"

# ---------- 1. IMPORTS ----------
import json
import re
import sys
import time
import unicodedata
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import loguniform, randint
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.utils import resample

# ---------- 2. PATHS + OPTIONAL COLAB SETUP ----------
if RUN_ON_COLAB:
    # !pip -q install torch transformers scikit-learn pandas matplotlib scipy
    from google.colab import files
    import zipfile
    import io

    print("Upload care_notes_corpus.csv")
    uploaded = files.upload()
    DATASET = Path("/content/care_notes_corpus.csv")
    for fname, raw in uploaded.items():
        if fname.lower().endswith(".csv"):
            DATASET.write_bytes(raw)
            break
    if not DATASET.is_file():
        raise FileNotFoundError("Upload care_notes_corpus.csv")

    FW = Path("/content/care_notes_nlp_framework")
    if not (FW / "nlp" / "rnn_classifier.py").is_file():
        print("Upload NLP_SevenModel_Colab.zip")
        up = files.upload()
        for fname, raw in up.items():
            if fname.lower().endswith(".zip"):
                with zipfile.ZipFile(io.BytesIO(raw)) as z:
                    z.extractall("/content")
                break
    sys.path.insert(0, str(FW))
    OUT_DIR = Path("/content/pipeline_results")
else:
    FW = Path(__file__).resolve().parent
    sys.path.insert(0, str(FW))
    DATASET = FW.parent / "Synthetic_CareNotes_Dataset" / "care_notes_corpus.csv"
    OUT_DIR = FW / "results" / "linear_seven_model_pipeline"

OUT_DIR.mkdir(parents=True, exist_ok=True)

from nlp.rnn_classifier import RNNTextClassifier
from nlp.transformer_classifier import TransformerTextClassifier

if FAST:
    RNN_EPOCHS, RNN_MAX_LEN = 3, 96
    TR_EPOCHS, TR_MAX_LEN, TR_BATCH = 1, 64, 16
else:
    RNN_EPOCHS, RNN_MAX_LEN = 5, 128
    TR_EPOCHS, TR_MAX_LEN, TR_BATCH = 2, 128, 16

rng = np.random.default_rng(RANDOM_STATE)
print("=" * 70)
print("NINE-STEP PIPELINE — SEVEN MODELS (linear, no custom functions)")
print("FAST =", FAST, " N_ITER =", N_ITER)
print("Dataset:", DATASET)
print("=" * 70)

# ---------- STEP 1 — Clean dataset ----------
print("\nSTEP 1 — Clean dataset")
df = pd.read_csv(DATASET)
required = ["note_text", "escalation_recommended", "mods_risk_level", "safeguarding_flag"]
missing = [c for c in required if c not in df.columns]
if missing:
    raise ValueError("Missing columns: " + str(missing))

df[TEXT_COL] = df[TEXT_COL].astype(str)
df[TEXT_COL] = df[TEXT_COL].map(lambda x: unicodedata.normalize("NFKC", x))
df[TEXT_COL] = df[TEXT_COL].str.replace("\r\n", "\n").str.replace("\r", "\n")
df[TEXT_COL] = df[TEXT_COL].str.replace(r"\s+", " ", regex=True).str.strip()
df[TEXT_COL] = df[TEXT_COL].str.replace(r"^Digital Social Care Record\s*[-–]\s*", "", regex=True)
df[TEXT_COL] = df[TEXT_COL].str.replace(r"^Copied from previous entry\s*[-–]\s*", "", regex=True)
df = df[df[TEXT_COL].str.len() >= 20].drop_duplicates(subset=[TEXT_COL]).copy()
df[LABEL_COL] = df[LABEL_COL].astype(int)
print("Rows after cleaning:", len(df))

# ---------- STEP 2 — 70/30 stratified split ----------
print("\nSTEP 2 — Train/test split 70/30")
train_df, test_df = train_test_split(
    df, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=df[LABEL_COL]
)
train_df = train_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)
print("Train:", len(train_df), " Test:", len(test_df))

# ---------- STEP 3 — Balance TRAINING set only ----------
print("\nSTEP 3 — Balance training set ONLY")
target_n = int(round(train_df[LABEL_COL].value_counts().mean()))
part0 = resample(
    train_df[train_df[LABEL_COL] == 0],
    replace=True,
    n_samples=target_n,
    random_state=RANDOM_STATE,
)
part1 = resample(
    train_df[train_df[LABEL_COL] == 1],
    replace=True,
    n_samples=target_n,
    random_state=RANDOM_STATE,
)
train_bal = (
    pd.concat([part0, part1], ignore_index=True)
    .sample(frac=1, random_state=RANDOM_STATE)
    .reset_index(drop=True)
)
print("Balanced train:", train_bal[LABEL_COL].value_counts().to_dict())
print("Test unchanged:", test_df[LABEL_COL].value_counts().to_dict())

train_text = train_bal[TEXT_COL].astype(str).tolist()
test_text = test_df[TEXT_COL].astype(str).tolist()
y_train = train_bal[LABEL_COL].astype(int).values
y_test = test_df[LABEL_COL].astype(int).values

risk_map = {"low": 0, "medium": 1, "high": 2}
train_struct = np.column_stack([
    train_bal["mods_risk_level"].map(lambda x: risk_map.get(str(x).lower(), 0)).values,
    train_bal["safeguarding_flag"].astype(int).values,
])
test_struct = np.column_stack([
    test_df["mods_risk_level"].map(lambda x: risk_map.get(str(x).lower(), 0)).values,
    test_df["safeguarding_flag"].astype(int).values,
])
struct_clf = LogisticRegression(max_iter=2000, class_weight="balanced", random_state=RANDOM_STATE)
struct_clf.fit(train_struct, y_train)
p_struct_test = struct_clf.predict_proba(test_struct)[:, 1]

# ---------- STEP 4 — TF-IDF + Logistic Regression ----------
print("\nSTEP 4 — TF-IDF + Logistic Regression")
logreg = Pipeline([
    ("tfidf", TfidfVectorizer(max_features=6000, ngram_range=(1, 2), sublinear_tf=True, min_df=2)),
    ("clf", LogisticRegression(max_iter=3000, class_weight="balanced", random_state=RANDOM_STATE)),
])
logreg.fit(train_text, y_train)
p_text_logreg = logreg.predict_proba(test_text)[:, 1]
p_comb_logreg = FUSION_TEXT * p_text_logreg + FUSION_STRUCT * p_struct_test
pred_logreg = (p_comb_logreg >= THRESHOLD).astype(int)
acc_logreg = accuracy_score(y_test, pred_logreg)
f1_logreg = f1_score(y_test, pred_logreg, zero_division=0)
prec_logreg = precision_score(y_test, pred_logreg, zero_division=0)
rec_logreg = recall_score(y_test, pred_logreg, zero_division=0)
print("  Accuracy:", round(acc_logreg, 4), " F1:", round(f1_logreg, 4))

# ---------- STEP 5 — LSTM, GRU, Bi-LSTM ----------
print("\nSTEP 5 — RNN models (LSTM, GRU, Bi-LSTM)")

print("  Training LSTM...")
lstm = RNNTextClassifier(
    architecture="lstm", epochs=RNN_EPOCHS, max_length=RNN_MAX_LEN,
    batch_size=32, hidden_dim=128, dropout=0.3, learning_rate=1e-3,
)
lstm.fit(train_text, y_train)
p_text_lstm = lstm.predict_proba(test_text)[:, list(lstm.classes_).index(1)]
p_comb_lstm = FUSION_TEXT * p_text_lstm + FUSION_STRUCT * p_struct_test
pred_lstm = (p_comb_lstm >= THRESHOLD).astype(int)
acc_lstm = accuracy_score(y_test, pred_lstm)
f1_lstm = f1_score(y_test, pred_lstm, zero_division=0)
prec_lstm = precision_score(y_test, pred_lstm, zero_division=0)
rec_lstm = recall_score(y_test, pred_lstm, zero_division=0)
print("  LSTM Accuracy:", round(acc_lstm, 4), " F1:", round(f1_lstm, 4))

print("  Training GRU...")
gru = RNNTextClassifier(
    architecture="gru", epochs=RNN_EPOCHS, max_length=RNN_MAX_LEN,
    batch_size=32, hidden_dim=128, dropout=0.3, learning_rate=1e-3,
)
gru.fit(train_text, y_train)
p_text_gru = gru.predict_proba(test_text)[:, list(gru.classes_).index(1)]
p_comb_gru = FUSION_TEXT * p_text_gru + FUSION_STRUCT * p_struct_test
pred_gru = (p_comb_gru >= THRESHOLD).astype(int)
acc_gru = accuracy_score(y_test, pred_gru)
f1_gru = f1_score(y_test, pred_gru, zero_division=0)
prec_gru = precision_score(y_test, pred_gru, zero_division=0)
rec_gru = recall_score(y_test, pred_gru, zero_division=0)
print("  GRU Accuracy:", round(acc_gru, 4), " F1:", round(f1_gru, 4))

print("  Training Bi-LSTM...")
bilstm = RNNTextClassifier(
    architecture="bilstm", epochs=RNN_EPOCHS, max_length=RNN_MAX_LEN,
    batch_size=32, hidden_dim=128, dropout=0.3, learning_rate=1e-3,
)
bilstm.fit(train_text, y_train)
p_text_bilstm = bilstm.predict_proba(test_text)[:, list(bilstm.classes_).index(1)]
p_comb_bilstm = FUSION_TEXT * p_text_bilstm + FUSION_STRUCT * p_struct_test
pred_bilstm = (p_comb_bilstm >= THRESHOLD).astype(int)
acc_bilstm = accuracy_score(y_test, pred_bilstm)
f1_bilstm = f1_score(y_test, pred_bilstm, zero_division=0)
prec_bilstm = precision_score(y_test, pred_bilstm, zero_division=0)
rec_bilstm = recall_score(y_test, pred_bilstm, zero_division=0)
print("  Bi-LSTM Accuracy:", round(acc_bilstm, 4), " F1:", round(f1_bilstm, 4))

# ---------- STEP 6 — DistilBERT, RoBERTa, ModernBERT ----------
print("\nSTEP 6 — Transformer models")

print("  Training DistilBERT...")
t0 = time.time()
distilbert = TransformerTextClassifier(
    model_name="distilbert-base-uncased",
    epochs=TR_EPOCHS, max_length=TR_MAX_LEN, batch_size=TR_BATCH, learning_rate=2e-5,
)
distilbert.fit(train_text, y_train)
p_text_distil = distilbert.predict_proba(test_text)[:, list(distilbert.classes_).index(1)]
p_comb_distil = FUSION_TEXT * p_text_distil + FUSION_STRUCT * p_struct_test
pred_distil = (p_comb_distil >= THRESHOLD).astype(int)
acc_distil = accuracy_score(y_test, pred_distil)
f1_distil = f1_score(y_test, pred_distil, zero_division=0)
prec_distil = precision_score(y_test, pred_distil, zero_division=0)
rec_distil = recall_score(y_test, pred_distil, zero_division=0)
print("  DistilBERT Accuracy:", round(acc_distil, 4), " F1:", round(f1_distil, 4), f" ({time.time()-t0:.0f}s)")

print("  Training RoBERTa...")
t0 = time.time()
roberta = TransformerTextClassifier(
    model_name="roberta-base",
    epochs=TR_EPOCHS, max_length=TR_MAX_LEN, batch_size=TR_BATCH, learning_rate=2e-5,
)
roberta.fit(train_text, y_train)
p_text_roberta = roberta.predict_proba(test_text)[:, list(roberta.classes_).index(1)]
p_comb_roberta = FUSION_TEXT * p_text_roberta + FUSION_STRUCT * p_struct_test
pred_roberta = (p_comb_roberta >= THRESHOLD).astype(int)
acc_roberta = accuracy_score(y_test, pred_roberta)
f1_roberta = f1_score(y_test, pred_roberta, zero_division=0)
prec_roberta = precision_score(y_test, pred_roberta, zero_division=0)
rec_roberta = recall_score(y_test, pred_roberta, zero_division=0)
print("  RoBERTa Accuracy:", round(acc_roberta, 4), " F1:", round(f1_roberta, 4), f" ({time.time()-t0:.0f}s)")

print("  Training ModernBERT...")
t0 = time.time()
modernbert = TransformerTextClassifier(
    model_name="answerdotai/ModernBERT-base",
    epochs=TR_EPOCHS, max_length=TR_MAX_LEN, batch_size=TR_BATCH, learning_rate=2e-5,
)
modernbert.fit(train_text, y_train)
p_text_modern = modernbert.predict_proba(test_text)[:, list(modernbert.classes_).index(1)]
p_comb_modern = FUSION_TEXT * p_text_modern + FUSION_STRUCT * p_struct_test
pred_modern = (p_comb_modern >= THRESHOLD).astype(int)
acc_modern = accuracy_score(y_test, pred_modern)
f1_modern = f1_score(y_test, pred_modern, zero_division=0)
prec_modern = precision_score(y_test, pred_modern, zero_division=0)
rec_modern = recall_score(y_test, pred_modern, zero_division=0)
print("  ModernBERT Accuracy:", round(acc_modern, 4), " F1:", round(f1_modern, 4), f" ({time.time()-t0:.0f}s)")

# ---------- Seven-model comparison (ranked by accuracy) ----------
print("\n--- SEVEN-MODEL COMPARISON (combined escalation accuracy) ---")
comparison = [
    {"model": "TF-IDF + LogReg", "accuracy": float(acc_logreg), "f1": float(f1_logreg),
     "precision": float(prec_logreg), "recall": float(rec_logreg)},
    {"model": "LSTM", "accuracy": float(acc_lstm), "f1": float(f1_lstm),
     "precision": float(prec_lstm), "recall": float(rec_lstm)},
    {"model": "GRU", "accuracy": float(acc_gru), "f1": float(f1_gru),
     "precision": float(prec_gru), "recall": float(rec_gru)},
    {"model": "Bi-LSTM", "accuracy": float(acc_bilstm), "f1": float(f1_bilstm),
     "precision": float(prec_bilstm), "recall": float(rec_bilstm)},
    {"model": "DistilBERT", "accuracy": float(acc_distil), "f1": float(f1_distil),
     "precision": float(prec_distil), "recall": float(rec_distil)},
    {"model": "RoBERTa", "accuracy": float(acc_roberta), "f1": float(f1_roberta),
     "precision": float(prec_roberta), "recall": float(rec_roberta)},
    {"model": "ModernBERT", "accuracy": float(acc_modern), "f1": float(f1_modern),
     "precision": float(prec_modern), "recall": float(rec_modern)},
]
comparison.sort(key=lambda x: x["accuracy"], reverse=True)
print(f"{'Model':20} {'Accuracy':>10} {'F1':>8} {'Precision':>10} {'Recall':>8}")
for row in comparison:
    print(f"{row['model']:20} {row['accuracy']:10.4f} {row['f1']:8.4f} {row['precision']:10.4f} {row['recall']:8.4f}")

# ---------- STEP 7 — Best two models ----------
print("\nSTEP 7 — Select best two models by accuracy")
best1_name = comparison[0]["model"]
best2_name = comparison[1]["model"]
def_acc1 = comparison[0]["accuracy"]
def_acc2 = comparison[1]["accuracy"]
print("Best 1:", best1_name, round(def_acc1, 4))
print("Best 2:", best2_name, round(def_acc2, 4))

# Validation split from balanced train (for transformer random-search selection)
tune_idx, val_idx = train_test_split(
    np.arange(len(train_bal)), test_size=0.20, random_state=RANDOM_STATE, stratify=y_train
)
train_tune_df = train_bal.iloc[tune_idx].reset_index(drop=True)
val_df = train_bal.iloc[val_idx].reset_index(drop=True)
train_text_tune = train_tune_df[TEXT_COL].astype(str).tolist()
val_text = val_df[TEXT_COL].astype(str).tolist()
y_train_tune = train_tune_df[LABEL_COL].astype(int).values
y_val = val_df[LABEL_COL].astype(int).values
val_struct = np.column_stack([
    val_df["mods_risk_level"].map(lambda x: risk_map.get(str(x).lower(), 0)).values,
    val_df["safeguarding_flag"].astype(int).values,
])
struct_tune = LogisticRegression(max_iter=2000, class_weight="balanced", random_state=RANDOM_STATE)
struct_tune.fit(
    np.column_stack([
        train_tune_df["mods_risk_level"].map(lambda x: risk_map.get(str(x).lower(), 0)).values,
        train_tune_df["safeguarding_flag"].astype(int).values,
    ]),
    y_train_tune,
)
p_struct_val = struct_tune.predict_proba(val_struct)[:, 1]

hf_map = {
    "DistilBERT": "distilbert-base-uncased",
    "RoBERTa": "roberta-base",
    "ModernBERT": "answerdotai/ModernBERT-base",
}
arch_map = {"LSTM": "lstm", "GRU": "gru", "Bi-LSTM": "bilstm"}
all_trials = []

# ---------- STEP 8a — Random search: BEST MODEL 1 ----------
print("\nSTEP 8a — Random search (independent):", best1_name)
t0 = time.time()
trials1 = []

if best1_name == "TF-IDF + LogReg":
    pipe1 = Pipeline([
        ("tfidf", TfidfVectorizer(max_features=6000, ngram_range=(1, 2), sublinear_tf=True, min_df=2)),
        ("clf", LogisticRegression(max_iter=3000, class_weight="balanced", random_state=RANDOM_STATE)),
    ])
    search1 = RandomizedSearchCV(
        pipe1,
        {
            "clf__C": loguniform(0.05, 20.0),
            "clf__class_weight": [None, "balanced"],
            "tfidf__max_features": randint(3000, 9000),
            "tfidf__ngram_range": [(1, 1), (1, 2), (1, 3)],
        },
        n_iter=N_ITER, cv=3, scoring="accuracy", n_jobs=-1, random_state=RANDOM_STATE,
    )
    search1.fit(train_text, y_train)
    best1 = search1.best_estimator_
    best1_params = search1.best_params_
    p_text_t1 = best1.predict_proba(test_text)[:, 1]
    for i, p in enumerate(search1.cv_results_["params"]):
        trials1.append({
            "trial": i + 1,
            "params": p,
            "cv_accuracy": float(search1.cv_results_["mean_test_score"][i]),
        })

elif best1_name in arch_map:
    best1_acc, best1, best1_params = -1.0, None, {}
    for trial in range(1, N_ITER + 1):
        ep = int(rng.choice([2, 3, 4]))
        lr = float(rng.choice([1e-4, 3e-4, 5e-4, 1e-3, 2e-3]))
        bs = int(rng.choice([16, 32]))
        hd = int(rng.choice([64, 128, 256]))
        drop = float(np.round(rng.uniform(0.2, 0.5), 2))
        ml = int(rng.choice([96, 128]))
        params = {
            "epochs": ep, "learning_rate": lr, "batch_size": bs,
            "hidden_dim": hd, "dropout": drop, "max_length": ml,
        }
        trial_clf = RNNTextClassifier(
            architecture=arch_map[best1_name], epochs=ep, max_length=ml,
            learning_rate=lr, batch_size=bs, hidden_dim=hd, dropout=drop,
        )
        trial_clf.fit(train_text, y_train)
        pt = trial_clf.predict_proba(test_text)[:, list(trial_clf.classes_).index(1)]
        pc = FUSION_TEXT * pt + FUSION_STRUCT * p_struct_test
        acc = accuracy_score(y_test, (pc >= THRESHOLD).astype(int))
        trials1.append({"trial": trial, "params": params, "accuracy": float(acc)})
        if acc > best1_acc:
            best1_acc, best1, best1_params = acc, trial_clf, params
    p_text_t1 = best1.predict_proba(test_text)[:, list(best1.classes_).index(1)]

else:
    best1_val, best1_params = -1.0, {}
    for trial in range(1, N_ITER + 1):
        lr = float(rng.choice([1e-5, 2e-5, 3e-5, 5e-5, 8e-5]))
        ep = int(rng.choice([1, 2] if FAST else [1, 2, 3]))
        bs = int(rng.choice([16, 32]))
        wd = float(rng.choice([0.0, 0.01, 0.05, 0.1]))
        drop = float(np.round(rng.uniform(0.05, 0.35), 2))
        ml = int(rng.choice([64, 96]))
        params = {
            "learning_rate": lr, "epochs": ep, "batch_size": bs,
            "weight_decay": wd, "dropout": drop, "max_length": ml,
        }
        trial_clf = TransformerTextClassifier(
            model_name=hf_map[best1_name], learning_rate=lr, epochs=ep,
            max_length=ml, batch_size=bs, weight_decay=wd, dropout=drop,
        )
        trial_clf.fit(train_text_tune, y_train_tune)
        pt = trial_clf.predict_proba(val_text)[:, list(trial_clf.classes_).index(1)]
        pc = FUSION_TEXT * pt + FUSION_STRUCT * p_struct_val
        val_acc = accuracy_score(y_val, (pc >= THRESHOLD).astype(int))
        trials1.append({"trial": trial, "params": params, "val_accuracy": float(val_acc)})
        if val_acc > best1_val:
            best1_val, best1_params = val_acc, params
    best1 = TransformerTextClassifier(
        model_name=hf_map[best1_name],
        learning_rate=best1_params["learning_rate"],
        epochs=best1_params["epochs"],
        max_length=best1_params["max_length"],
        batch_size=best1_params["batch_size"],
        weight_decay=best1_params["weight_decay"],
        dropout=best1_params["dropout"],
    )
    best1.fit(train_text, y_train)
    p_text_t1 = best1.predict_proba(test_text)[:, list(best1.classes_).index(1)]

p_comb_t1 = FUSION_TEXT * p_text_t1 + FUSION_STRUCT * p_struct_test
pred_t1 = (p_comb_t1 >= THRESHOLD).astype(int)
acc_t1 = accuracy_score(y_test, pred_t1)
f1_t1 = f1_score(y_test, pred_t1, zero_division=0)
prec_t1 = precision_score(y_test, pred_t1, zero_division=0)
rec_t1 = recall_score(y_test, pred_t1, zero_division=0)
print("  Best params:", best1_params)
print("  Test accuracy:", round(acc_t1, 4), " F1:", round(f1_t1, 4), f" ({time.time()-t0:.0f}s)")
all_trials += [{"model": best1_name, **t} for t in trials1]


In [ ]:
import os, sys
os.chdir("/content/care_notes_nlp_framework")
sys.path.insert(0, "/content/care_notes_nlp_framework")
%run -i run_pipeline.py

============================================================
Care Notes NLP Framework — Domiciliary & Care Home
============================================================
Dataset: /content/Synthetic_CareNotes_Dataset
Results: /content/care_notes_nlp_framework/results
Learned-classifier backend: TF-IDF + Logistic Regression

Training on 2800 notes...
Evaluating...

Care Notes NLP Framework — Evaluation Summary
=======================================================
Gold subset (n=400)
  Entity F1:     0.4250  (P=0.3053, R=0.6991)
  Relation F1:   0.0252  (P=0.0164, R=0.0548)

Test split (n=600)
  Note type acc: 0.1633
  Setting acc:   1.0000
  Escalation F1: 0.8522  (threshold=0.6)
  Escalation AUROC: 0.9562

Initial figures: entity_f1_by_label.png, escalation_model_comparison.png
Generating figures...
Output: /content/care_notes_nlp_framework/results/figures

Generated 23 figures:

  - figures/Fig_4_10_Escalation_Model_Comparison.png
  - figures/Fig_4_11_Escalation_ROC_Curve.png
  - figures/Fig_4_12_Escalation_PR_Curve.png
  - figures/Fig_4_13_Escalation_Confusion_Matrix.png
  - figures/Fig_4_14_Escalation_Probability_Distribution.png
  - figures/Fig_4_15_Subgroup_Escalation_F1.png
  - figures/Fig_4_16_Note_Type_Confusion_Matrix.png
  - figures/Fig_4_17_CDS_Escalation_Scores.png
  - figures/Fig_4_18_Alerts_By_Setting.png
  - figures/Fig_4_19_Entities_By_Setting.png
  - figures/Fig_4_1_Pipeline_Architecture.png
  - figures/Fig_4_20_Escalation_vs_Entities_Scatter.png
  - figures/Fig_4_21_Gold_Annotation_Stats.png
  - figures/Fig_4_22_Results_Dashboard.png
  - figures/Fig_4_23_Setting_NoteType_Heatmap.png
  - figures/Fig_4_2_Dataset_Overview.png
  - figures/Fig_4_3_Note_Types_Distribution.png
  - figures/Fig_4_4_MODS_Risk_Distribution.png
  - figures/Fig_4_5_Entity_Metrics_By_Label.png
  - figures/Fig_4_6_Entity_F1_By_Label.png
  - figures/Fig_4_7_Entity_Overall_Metrics.png
  - figures/Fig_4_8_Relation_Metrics_By_Type.png
  - figures/Fig_4_9_Relation_Overall_F1.png

Also copied to: /content/care_notes_nlp_framework/results
Index: /content/care_notes_nlp_framework/results/figures/FIGURE_INDEX.txt
Statistical validation...
STATISTICAL VALIDATION SUMMARY
==================================================
Bootstrap: 2000 resamples, 95% CI

ESCALATION (combined model, test n=38)
  F1:    0.8522  [0.8209, 0.8803]
  AUROC: 0.9562  [0.9417, 0.9692]

ENTITY F1 (gold n=80): 0.4250  [0.3989, 0.4492]
RELATION F1 (gold n=80): 0.0252  [0.0169, 0.0345]

McNEMAR TESTS (escalation, paired on test set)
  nlp_vs_combined: p=0.0000 ? Model B significantly better than A
  structured_vs_combined: p=0.0000 ? Model A significantly better than B
  nlp_vs_structured: p=0.0000 ? Model B significantly better than A

BOOTSTRAP F1 DIFFERENCE (combined ? comparator)
  combined_vs_nlp_f1: diff=0.6518, p=0.0000, significant=True
  combined_vs_structured_f1: diff=-0.0408, p=0.0000, significant=True
  structured_vs_nlp_f1: diff=0.6925, p=0.0000, significant=True

Saved: /content/care_notes_nlp_framework/results/statistical_validation_report.json
Saved: /content/care_notes_nlp_framework/results/statistical_validation_table.csv
Figures: Fig_4_24_Escalation_Bootstrap_CI.png, Fig_4_25_NER_Relation_Bootstrap_CI.png, Fig_4_26_McNemar_Paired_Tests.png, Fig_4_27_Bootstrap_F1_Differences.png

Entity F1 (gold): 0.4250 | Relation F1 (gold): 0.0252 | Escalation F1 (test): 0.8522

Done. Outputs in: /content/care_notes_nlp_framework/results
All figures in: /content/care_notes_nlp_framework/results/figures

In [ ]:
!python /content/care_notes_nlp_framework/run_complete_model_comparison.py --fast

Running 7 models:
  - TF-IDF + LogReg (Traditional ML)
  - LSTM (Deep Learning (RNN))
  - GRU (Deep Learning (RNN))
  - Bi-LSTM (Deep Learning (RNN))
  - DistilBERT (Transformer)
  - RoBERTa (Transformer)
  - ModernBERT (Transformer)
Hardware: GPU detected — transformer models will train much faster.
Estimated total time: ~45–90 min for all 7 models (full) or ~20–30 min (--fast)


=== LSTM ===
  Training for escalation...
  Training for note-type...
  Done in 3.7s

=== GRU ===
  Training for escalation...
  Training for note-type...
  Done in 1.7s

=== Bi-LSTM ===
  Training for escalation...
  Training for note-type...
  Done in 2.1s

=== DistilBERT (distilbert-base-uncased) ===
  Fine-tuning for escalation...
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100% 100/100 [00:00<00:00, 8095.24it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
{'loss': '0.684', 'grad_norm': '1.302', 'learning_rate': '1.44e-05', 'epoch': '0.2857'}
{'loss': '0.6865', 'grad_norm': '1.339', 'learning_rate': '8.686e-06', 'epoch': '0.5714'}
{'loss': '0.6674', 'grad_norm': '0.5653', 'learning_rate': '2.971e-06', 'epoch': '0.8571'}
{'train_runtime': '7.527', 'train_samples_per_second': '372', 'train_steps_per_second': '23.25', 'train_loss': '0.6787', 'epoch': '1'}
100% 175/175 [00:07<00:00, 23.25it/s]
100% 75/75 [00:00<00:00, 128.04it/s]
  Fine-tuning for note-type...
Loading weights: 100% 100/100 [00:00<00:00, 5104.11it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
{'loss': '2.171', 'grad_norm': '2.844', 'learning_rate': '1.44e-05', 'epoch': '0.2857'}
{'loss': '2.047', 'grad_norm': '3.252', 'learning_rate': '8.686e-06', 'epoch': '0.5714'}
{'loss': '1.906', 'grad_norm': '3.207', 'learning_rate': '2.971e-06', 'epoch': '0.8571'}
{'train_runtime': '7.324', 'train_samples_per_second': '382.3', 'train_steps_per_second': '23.89', 'train_loss': '2.018', 'epoch': '1'}
100% 175/175 [00:07<00:00, 23.89it/s]
100% 75/75 [00:00<00:00, 132.48it/s]
  Done in 25.4s

=== RoBERTa (roberta-base) ===
  Fine-tuning for escalation...
Loading weights: 100% 197/197 [00:00<00:00, 5496.06it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
{'loss': '0.6973', 'grad_norm': '2.935', 'learning_rate': '1.44e-05', 'epoch': '0.2857'}
{'loss': '0.6835', 'grad_norm': '3.232', 'learning_rate': '8.686e-06', 'epoch': '0.5714'}
{'loss': '0.6769', 'grad_norm': '1.068', 'learning_rate': '2.971e-06', 'epoch': '0.8571'}
{'train_runtime': '13.53', 'train_samples_per_second': '206.9', 'train_steps_per_second': '12.93', 'train_loss': '0.6841', 'epoch': '1'}
100% 175/175 [00:13<00:00, 12.93it/s]
100% 75/75 [00:00<00:00, 75.46it/s]
  Fine-tuning for note-type...
Loading weights: 100% 197/197 [00:00<00:00, 17298.09it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
{'loss': '2.18', 'grad_norm': '3.652', 'learning_rate': '1.44e-05', 'epoch': '0.2857'}
{'loss': '2.143', 'grad_norm': '5.365', 'learning_rate': '8.686e-06', 'epoch': '0.5714'}
{'loss': '2.021', 'grad_norm': '5.247', 'learning_rate': '2.971e-06', 'epoch': '0.8571'}
{'train_runtime': '13.4', 'train_samples_per_second': '209', 'train_steps_per_second': '13.06', 'train_loss': '2.087', 'epoch': '1'}
100% 175/175 [00:13<00:00, 13.06it/s]
100% 75/75 [00:00<00:00, 75.25it/s]
  Done in 35.4s

=== ModernBERT (answerdotai/ModernBERT-base) ===
  Fine-tuning for escalation...
Loading weights: 100% 136/136 [00:00<00:00, 5803.08it/s]
[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
{'loss': '0.7264', 'grad_norm': '2.96', 'learning_rate': '1.44e-05', 'epoch': '0.2857'}
{'loss': '0.7114', 'grad_norm': '6.409', 'learning_rate': '8.686e-06', 'epoch': '0.5714'}
{'loss': '0.6791', 'grad_norm': '5.05', 'learning_rate': '2.971e-06', 'epoch': '0.8571'}
{'train_runtime': '20.67', 'train_samples_per_second': '135.4', 'train_steps_per_second': '8.466', 'train_loss': '0.7013', 'epoch': '1'}
100% 175/175 [00:20<00:00,  8.47it/s]
100% 75/75 [00:01<00:00, 39.25it/s]
  Fine-tuning for note-type...
Loading weights: 100% 136/136 [00:00<00:00, 5445.43it/s]
[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
{'loss': '2.164', 'grad_norm': '16', 'learning_rate': '1.44e-05', 'epoch': '0.2857'}
{'loss': '1.994', 'grad_norm': '10.87', 'learning_rate': '8.686e-06', 'epoch': '0.5714'}
{'loss': '1.823', 'grad_norm': '8.026', 'learning_rate': '2.971e-06', 'epoch': '0.8571'}
{'train_runtime': '20.9', 'train_samples_per_second': '134', 'train_steps_per_second': '8.373', 'train_loss': '1.96', 'epoch': '1'}
100% 175/175 [00:20<00:00,  8.37it/s]
100% 75/75 [00:01<00:00, 41.07it/s]
  Done in 51.2s

============================================================
WINNERS (individual models):
  escalation_text_only: DistilBERT
  escalation_combined: GRU
  note_type: TF-IDF + LogReg
  best_overall_escalation: GRU

CATEGORY WINNERS (by mean F1):
  escalation_text_only: Deep Learning (RNN)
  escalation_combined: Deep Learning (RNN)
  note_type: Traditional ML

Saved: /content/care_notes_nlp_framework/results/complete_model_comparison_report.json
Table: /content/care_notes_nlp_framework/results/complete_model_comparison_table.csv
Category table: /content/care_notes_nlp_framework/results/complete_model_comparison_by_category.csv
Figures: /content/care_notes_nlp_framework/results/complete_model_comparison_figures

In [ ]:
from pathlib import Path
from google.colab import files
import zipfile

results = Path("/content/care_notes_nlp_framework/results")
out_zip = Path("/content/NLP_Results.zip")
with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as z:
    for f in results.rglob("*"):
        if f.is_file() and f.suffix.lower() in {".json", ".csv", ".png", ".txt"}:
            z.write(f, arcname=str(f.relative_to("/content")))
print("Downloading", out_zip)
files.download(str(out_zip))

Downloading /content/NLP_Results.zip